---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mipdevpc/public_html/resume-adrian
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH